#!/usr/bin/env bash
# music-stack native setup for macOS (Intel x86_64 or Apple Silicon).
# Idempotent. Installs Navidrome + Lidarr + ffmpeg + qBittorrent via Homebrew
# and direct downloads, registers LaunchAgents, and configures Lidarr via its API.
#
#   bash scripts/macos/setup.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common/lib.sh
source "$SCRIPT_DIR/../common/lib.sh"

ms_require_cmd curl
ms_require_cmd xcode-select

# ---------------------------------------------------------------- settings --
ms_ensure_settings
QBIT_PASSWORD="$(ms_setting 'QBIT_PASSWORD')"

MACHINE="$(uname -m)"
case "$MACHINE" in
  x86_64)     LIDARR_ARCH="x64"  ;;
  arm64)      LIDARR_ARCH="arm64" ;;
  *)          ms_die "unsupported macOS architecture: $MACHINE" ;;
esac
ND_ARCH="$(ms_navidrome_arch "$MACHINE")"

MUSIC_DIR="$(ms_setting_path 'MUSIC_DIR' "$HOME/Music")"
DATA_DIR="$(ms_setting_path 'DATA_DIR' "$HOME/Library/Application Support/music-stack")"
DOWNLOAD_DIR="$(ms_setting_path 'DOWNLOAD_DIR' "$DATA_DIR/downloads")"
ND_PORT="$(ms_setting 'NAVIDROME_PORT' '4533')"
LIDARR_PORT="$(ms_setting 'LIDARR_PORT' '8686')"
QBIT_PORT="$(ms_setting 'QBIT_PORT' '8080')"
QBIT_USER="$(ms_setting 'QBIT_USER' 'admin')"
LIDARR_KEY="$(ms_setting 'LIDARR_API_KEY')"
[[ -n "$LIDARR_KEY" ]] || LIDARR_KEY="$(ms_random_hex 16)"
SCAN_SCHEDULE="$(ms_setting 'NAVIDROME_SCAN_SCHEDULE')"

ND_TOML="$DATA_DIR/navidrome/navidrome.toml"
LIDARR_APP="/Applications/Lidarr.app"
LIDARR_DATA="$DATA_DIR/lidarr"
LIDARR_LAUNCHD="$HOME/Library/LaunchAgents"
LIDARR_PLIST="$LIDARR_LAUNCHD/com.musicstack.lidarr.plist"
ND_PLIST="$LIDARR_LAUNCHD/com.musicstack.navidrome.plist"
QBIT_CONF="$HOME/Library/Preferences/qBittorrent/qBittorrent.conf"

mkdir -p "$MUSIC_DIR" "$DOWNLOAD_DIR" "$DATA_DIR/navidrome" "$LIDARR_DATA" "$LIDARR_LAUNCHD"

# ----------------------------------------------------------- prerequisites --
ms_log "Checking Command Line Tools..."
xcode-select -p >/dev/null 2>&1 || {
  ms_warn "Installing Command Line Tools (GUI prompt will appear). Re-run this script afterwards."
  xcode-select --install
  exit 1
}

if ! command -v brew >/dev/null 2>&1; then
  ms_log "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  # Homebrew on Intel loads into /usr/local; on ARM into /opt/homebrew.
  if [[ "$MACHINE" == "arm64" ]]; then eval "$(/opt/homebrew/bin/brew shellenv)"; fi
fi

ms_log "Installing ffmpeg via Homebrew..."
brew install ffmpeg

ms_log "Installing qBittorrent via Homebrew..."
brew install --cask qbittorrent

if ! command -v python3 >/dev/null 2>&1; then
  ms_log "Installing python3 via Homebrew..."
  brew install python
fi
PYTHON="$(command -v python3)"

BREW_PREFIX="$(brew --prefix)"
ND_BIN="$BREW_PREFIX/bin/navidrome"

# -------------------------------------------------------------- navidrome --
if [[ ! -x "$ND_BIN" ]]; then
  ms_log "Downloading latest Navidrome ($ND_ARCH)..."
  read -r ND_TAG ND_URL < <(ms_latest_navidrome darwin "$ND_ARCH")
  TMP="$(mktemp -d)"
  ms_download "$ND_URL" "$TMP/navidrome.tar.gz"
  tar -xzf "$TMP/navidrome.tar.gz" -C "$TMP"
  sudo install -m 0755 "$TMP/navidrome" "$BREW_PREFIX/bin/navidrome"
  rm -rf "$TMP"
  ms_log "Installed Navidrome $ND_TAG"
fi

{
  echo "# generated by music-stack"
  echo "LogLevel = 'info'"
  echo "Address = '0.0.0.0'"
  echo "Port = $ND_PORT"
  echo "MusicFolder = '$MUSIC_DIR'"
  echo "DataFolder = '$DATA_DIR/navidrome'"
  [[ -n "$SCAN_SCHEDULE" ]] && echo "Scanner.Schedule = '$SCAN_SCHEDULE'"
} > "$ND_TOML"
ms_log "Wrote navidrome.toml (music: $MUSIC_DIR)"

# ------------------------------------------------------------------ lidarr --
LIDARR_APP="/Applications/Lidarr.app"
if [[ ! -d "$LIDARR_APP" ]]; then
  ms_log "Downloading Lidarr ($LIDARR_ARCH)..."
  TMP="$(mktemp -d)"
  ms_download "$(ms_latest_lidarr osx "$LIDARR_ARCH")" "$TMP/lidarr.tar.gz"
  tar -xzf "$TMP/lidarr.tar.gz" -C "$TMP"
  sudo mkdir -p /Applications
  sudo mv "$TMP/Lidarr/Lidarr.app" "$LIDARR_APP"
  sudo xattr -dr com.apple.quarantine "$LIDARR_APP"
  rm -rf "$TMP"
  ms_log "Installed Lidarr to $LIDARR_APP"
fi
LIDARR_BIN="$LIDARR_APP/Contents/MacOS/Lidarr"

if [[ ! -f "$LIDARR_DATA/config.xml" ]]; then
  cat > "$LIDARR_DATA/config.xml" <<EOF
<Config>
  <Port>$LIDARR_PORT</Port>
  <BindAddress>*</BindAddress>
  <ApiKey>$LIDARR_KEY</ApiKey>
  <UrlBase></UrlBase>
  <UpdateMechanism>External</UpdateMechanism>
  <LaunchBrowser>False</LaunchBrowser>
  <LogLevel>info</LogLevel>
</Config>
EOF
  ms_log "Wrote Lidarr config.xml (port $LIDARR_PORT)"
fi

# ---------------------------------------------------------- qbittorrent ui --
QBIT_HASH="$(printf 'WebUI API:%s' "$QBIT_PASSWORD" | md5 -q)"
mkdir -p "$(dirname "$QBIT_CONF")"
if [[ ! -f "$QBIT_CONF" ]] || ! grep -q 'WebUI\\Enabled=true' "$QBIT_CONF"; then
  cat > "$QBIT_CONF" <<EOF
[LegalNotice]
Accepted=true
[Preferences]
WebUI\\Enabled=true
WebUI\\Port=$QBIT_PORT
WebUI\\Username=$QBIT_USER
WebUI\\Password=@ByteArray($QBIT_HASH)
WebUI\\LocalHostAuth=false
Session\\DefaultSavePath=$DOWNLOAD_DIR
Session\\TempPath=$DOWNLOAD_DIR
EOF
  ms_log "Pre-seeded qBittorrent WebUI config (port $QBIT_PORT)"
fi

# ------------------------------------------------------------- launchagents --
cat > "$ND_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.musicstack.navidrome</string>
  <key>ProgramArguments</key>
  <array>
    <string>$ND_BIN</string>
    <string>--configfile</string>
    <string>$ND_TOML</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict></plist>
EOF

cat > "$LIDARR_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.musicstack.lidarr</string>
  <key>ProgramArguments</key>
  <array>
    <string>$LIDARR_BIN</string>
    <string>-data=$LIDARR_DATA</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict></plist>
EOF

for label in com.musicstack.navidrome com.musicstack.lidarr; do
  launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
done
launchctl bootstrap "gui/$(id -u)" "$ND_PLIST"
launchctl bootstrap "gui/$(id -u)" "$LIDARR_PLIST"
ms_log "LaunchAgents registered (auto-start at login)"

# -------------------------------------------------------- lidarr post-config --
ms_configure_lidarr "$LIDARR_KEY" "$LIDARR_PORT" "$MS_SETTINGS" "$PYTHON"

# ------------------------------------------------------------------ summary --
cat <<EOF

======================================================================
 music-stack installed
======================================================================
 Navidrome : http://localhost:$ND_PORT   (create your admin on first visit)
 Lidarr    : http://localhost:$LIDARR_PORT
 qBittorrent WebUI: http://localhost:$QBIT_PORT   (user: $QBIT_USER)
 Music dir : $MUSIC_DIR

 First steps:
  1. Open Navidrome and create the admin account.
  2. Open Lidarr -> Settings -> Import Lists, add Last.fm/Spotify to pull in your artists.
  3. Lidarr Settings -> Indexers to add trackers (see config/indexers.json).
  4. Enable qBittorrent 'start on login' in its Preferences if you want it always-on.
======================================================================
EOF
