#!/usr/bin/env bash
# music-stack native setup for Raspberry Pi OS (Lite).
# Idempotent. Detects armv7 (Pi 2/3/Zero 2) vs arm64 (Pi 4/5), downloads the right
# Navidrome + Lidarr builds, installs ffmpeg + qbittorrent-nox, registers systemd
# services, and configures Lidarr via its API. Run as root:
#
#   sudo bash scripts/raspberry-pi/setup.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common/lib.sh
source "$SCRIPT_DIR/../common/lib.sh"

ms_require_cmd curl

[[ "$EUID" -eq 0 ]] || ms_die "run as root: sudo bash scripts/raspberry-pi/setup.sh"

# ---------------------------------------------------------------- settings --
[[ -n "$MS_SETTINGS" && -f "$MS_SETTINGS" ]] \
  || ms_die "settings.env not found. Copy settings.env.example to settings.env and set QBIT_PASSWORD."

QBIT_PASSWORD="$(ms_setting 'QBIT_PASSWORD')"
[[ -n "$QBIT_PASSWORD" ]] || ms_die "QBIT_PASSWORD is empty in $MS_SETTINGS"

MACHINE="$(uname -m)"
case "$MACHINE" in
  aarch64|arm64)
    ND_ARCH="arm64"; LIDARR_ARCH="arm64" ;;
  armv7l|armv6l)
    ND_ARCH="armv7"; LIDARR_ARCH="arm" ;;
  *)
    ms_die "unsupported architecture for Raspberry Pi: $MACHINE" ;;
esac
ms_log "Detected $MACHINE -> Navidrome $ND_ARCH / Lidarr $LIDARR_ARCH"

MUSIC_DIR="$(ms_setting_path 'MUSIC_DIR' '/mnt/music')"
DATA_DIR="$(ms_setting_path 'DATA_DIR' '/var/lib/music-stack')"
DOWNLOAD_DIR="$(ms_setting_path 'DOWNLOAD_DIR' "$DATA_DIR/downloads")"
ND_PORT="$(ms_setting 'NAVIDROME_PORT' '4533')"
LIDARR_PORT="$(ms_setting 'LIDARR_PORT' '8686')"
QBIT_PORT="$(ms_setting 'QBIT_PORT' '8080')"
QBIT_USER="$(ms_setting 'QBIT_USER' 'admin')"
LIDARR_KEY="$(ms_setting 'LIDARR_API_KEY')"
[[ -n "$LIDARR_KEY" ]] || LIDARR_KEY="$(ms_random_hex 16)"
SCAN_SCHEDULE="$(ms_setting 'NAVIDROME_SCAN_SCHEDULE')"

SVC_USER="music"
ND_TOML="$DATA_DIR/navidrome/navidrome.toml"
LIDARR_DATA="$DATA_DIR/lidarr"
LIDARR_HOME="/opt/Lidarr"
QBIT_HOME="$DATA_DIR/.config/qBittorrent"
QBIT_CONF="$QBIT_HOME/qBittorrent.conf"

# ------------------------------------------------------------- dependencies --
ms_log "apt-get update..."
apt-get update

ms_log "Installing ffmpeg, qbittorrent-nox, python3..."
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  ffmpeg qbittorrent-nox python3

# Dedicated service user (no login) with home under DATA_DIR.
if ! id -u "$SVC_USER" >/dev/null 2>&1; then
  ms_log "Creating service user '$SVC_USER'..."
  useradd -r -m -d "$DATA_DIR" -s /usr/sbin/nologin "$SVC_USER"
fi

mkdir -p "$MUSIC_DIR" "$DOWNLOAD_DIR" "$DATA_DIR/navidrome" "$LIDARR_DATA" "$QBIT_HOME"
chown -R "$SVC_USER:$SVC_USER" "$DATA_DIR" "$MUSIC_DIR"
chmod 0750 "$DATA_DIR"

# -------------------------------------------------------------- navidrome --
if [[ ! -x /usr/local/bin/navidrome ]]; then
  ms_log "Downloading latest Navidrome ($ND_ARCH)..."
  read -r ND_TAG ND_URL < <(ms_latest_navidrome linux "$ND_ARCH")
  TMP="$(mktemp -d)"
  ms_download "$ND_URL" "$TMP/navidrome.tar.gz"
  tar -xzf "$TMP/navidrome.tar.gz" -C "$TMP"
  install -m 0755 "$TMP/navidrome" /usr/local/bin/navidrome
  rm -rf "$TMP"
  ms_log "Installed Navidrome $ND_TAG"
fi

{
  echo "# generated by music-stack"
  echo "LogLevel = 'info'"
  echo "Address = '0.0.0.0'"
  echo "Port = $ND_PORT"
  echo "MusicFolder = '$MUSIC_DIR'"
  echo "DataFolder = '$DATA_DIR/navidrome'"
  [[ -n "$SCAN_SCHEDULE" ]] && echo "Scanner.Schedule = '$SCAN_SCHEDULE'"
} > "$ND_TOML"
chown "$SVC_USER:$SVC_USER" "$ND_TOML"
ms_log "Wrote navidrome.toml (music: $MUSIC_DIR)"

# ------------------------------------------------------------------ lidarr --
if [[ ! -d "$LIDARR_HOME/Lidarr" ]]; then
  ms_log "Downloading Lidarr ($LIDARR_ARCH)..."
  TMP="$(mktemp -d)"
  ms_download "$(ms_latest_lidarr linux "$LIDARR_ARCH")" "$TMP/lidarr.tar.gz"
  tar -xzf "$TMP/lidarr.tar.gz" -C "$TMP"
  mkdir -p /opt
  mv "$TMP/Lidarr" "$LIDARR_HOME"
  rm -rf "$TMP"
  ms_log "Installed Lidarr to $LIDARR_HOME"
fi

if [[ ! -f "$LIDARR_DATA/config.xml" ]]; then
  cat > "$LIDARR_DATA/config.xml" <<EOF
<Config>
  <Port>$LIDARR_PORT</Port>
  <BindAddress>*</BindAddress>
  <ApiKey>$LIDARR_KEY</ApiKey>
  <UrlBase></UrlBase>
  <UpdateMechanism>External</UpdateMechanism>
  <LaunchBrowser>False</LaunchBrowser>
  <LogLevel>info</LogLevel>
</Config>
EOF
  chown "$SVC_USER:$SVC_USER" "$LIDARR_DATA/config.xml"
  ms_log "Wrote Lidarr config.xml (port $LIDARR_PORT)"
fi

# ---------------------------------------------------------- qbittorrent-nox --
QBIT_HASH="$(printf 'WebUI API:%s' "$QBIT_PASSWORD" | md5sum | awk '{print $1}')"
if [[ ! -f "$QBIT_CONF" ]] || ! grep -q 'WebUI\\Enabled=true' "$QBIT_CONF"; then
  cat > "$QBIT_CONF" <<EOF
[LegalNotice]
Accepted=true
[Preferences]
WebUI\\Enabled=true
WebUI\\Port=$QBIT_PORT
WebUI\\Username=$QBIT_USER
WebUI\\Password=@ByteArray($QBIT_HASH)
WebUI\\LocalHostAuth=false
Session\\DefaultSavePath=$DOWNLOAD_DIR
Session\\TempPath=$DOWNLOAD_DIR
EOF
  chown -R "$SVC_USER:$SVC_USER" "$QBIT_HOME"
  ms_log "Pre-seeded qBittorrent WebUI config (port $QBIT_PORT)"
fi

# --------------------------------------------------------------- systemd --
cat > /etc/systemd/system/navidrome.service <<EOF
[Unit]
Description=Navidrome Music Server
After=network-online.target
Wants=network-online.target

[Service]
User=$SVC_USER
Group=$SVC_USER
Environment=HOME=$DATA_DIR
ExecStart=/usr/local/bin/navidrome --configfile $ND_TOML
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/lidarr.service <<EOF
[Unit]
Description=Lidarr Music Collection Manager
After=network-online.target
Wants=network-online.target

[Service]
User=$SVC_USER
Group=$SVC_USER
Environment=HOME=$DATA_DIR
ExecStart=$LIDARR_HOME/Lidarr -data=$LIDARR_DATA
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/qbittorrent-nox.service <<EOF
[Unit]
Description=qBittorrent-nox (music-stack)
After=network-online.target
Wants=network-online.target

[Service]
User=$SVC_USER
Group=$SVC_USER
Environment=HOME=$DATA_DIR
ExecStart=/usr/bin/qbittorrent-nox --webui-port=$QBIT_PORT
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
for svc in navidrome lidarr qbittorrent-nox; do
  systemctl enable "$svc" >/dev/null 2>&1 || true
  systemctl restart "$svc" || true
done
ms_log "systemd services enabled and started"

# -------------------------------------------------------- lidarr post-config --
ms_configure_lidarr "$LIDARR_KEY" "$LIDARR_PORT" "$MS_SETTINGS" "$(command -v python3)"

# ------------------------------------------------------------------ summary --
cat <<EOF

======================================================================
 music-stack installed
======================================================================
 Navidrome : http://localhost:$ND_PORT   (create your admin on first visit)
 Lidarr    : http://localhost:$LIDARR_PORT
 qBittorrent WebUI: http://localhost:$QBIT_PORT   (user: $QBIT_USER)
 Music dir : $MUSIC_DIR   (owned by user '$SVC_USER')

 First steps:
  1. Open Navidrome and create the admin account.
  2. Open Lidarr -> Settings -> Import Lists, add Last.fm/Spotify to pull in your artists.
  3. Lidarr Settings -> Indexers to add trackers (see config/indexers.json).
  4. If MUSIC_DIR is an external drive, ensure it is mounted at boot (e.g. fstab).
======================================================================
EOF
